name: "publish package to npm"

on: push

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org
      # - name: "Setup FFmpeg"
      #   uses: FedericoCarboni/setup-ffmpeg@v3
      # - name: Setup yt-dlp
      #   uses: AnimMouse/setup-yt-dlp@v1
      - name: Cache and install dependencies
        id: cache
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci
      - name: build
        run: npm run build
      # - name: test
      #   run: npx vitest run
      - name: publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
        run: npm publish --access public
